name: Build
on: 
  push

env:
  registry: ghcr.io/netwarlan
  image: tf2
  tag: latest

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Image
        run: |
          docker build . --tag ${{ env.registry }}/${{ env.image }}:${{ env.tag }}
          docker push ${{ env.registry }}/${{ env.image }}:${{ env.tag }}