name: Build
on: 
  push

env:
  registry: ghcr.io/netwarlan
  image: tf2
  branch: ${{ github.head_ref || github.ref_name }}

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      
      - name: Login to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Publish Image
        run: |
          if [ ${{ env.branch == "main" ]; then
            echo "branch=latest" >> $GITHUB_ENV
          }
          docker build . --tag ${{ env.registry }}/${{ env.image }}:${{ env.branch }}
          docker push ${{ env.registry }}/${{ env.image }}:${{ env.branch }}